---
- name: make a build dir
  file: state=directory name=/root/solr-nocloud-nohdfs-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/solr-nocloud-nohdfs-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/solr-nocloud-nohdfs-dockerized/start.sh mode=0755

- name: build a Docker image for Solr
  command: docker build -t gitinsky/solr-nocloud-nohdfs:0.1.1 --rm /root/solr-nocloud-nohdfs-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/solr-nocloud-nohdfs:latest --rm /root/solr-nocloud-nohdfs-dockerized
